### ISSUE TITLE
Failing build due to ?

### ISSUE THREAD

**Issue by matt-chan** [theochem/horton#227]
The build fails maybe because of a sphinx update? Or was releaseinfo.py changed? @tovrstra any idea?

horton/doc$ make html gives:
```
# Sphinx version: 1.5.2
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python3.5/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 76, in <module>
    ri = get_releaseinfo()
  File "/home/mattchan/Documents/Backup/pycharm/horton/doc/releaseinfo.py", line 30, in get_releaseinfo
    if '-' in describe:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by matt-chan** [comment]
Did the documentation always build using Python 3?

**Comment by tovrstra** [comment]
It didn't. On which environment do you see this? It may depend on how sphinx was installed.

**Comment by tovrstra** [comment]
I'm going to close this. We currently use Python 2.7, which is clearly stated in the docs. I you start using Python 3 instead, it is normal that you run into problems.
