### ISSUE TITLE
Issues with Ubuntu 18.04

### ISSUE THREAD

**Issue by panchajaviera** [theochem/horton#287]
Hi, I installed Horton on Ubuntu 18.04 and when I run nosetests, it shows me six errors, which are detailed at the bottom.

Is it possible to fix or should I try with another version of Ubuntu (16.04)?

Thanks!

```
======================================================================
ERROR: horton.part.test.test_proatomdb.test_db_basics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/test/test_proatomdb.py", line 31, in test_db_basics
    padb = ProAtomDB.from_refatoms(numbers=[8, 1], max_cation=1, max_anion=1)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

======================================================================
ERROR: horton.part.test.test_proatomdb.test_io_group
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/test/test_proatomdb.py", line 102, in test_io_group
    padb1 = ProAtomDB.from_refatoms(numbers=[1, 6], max_cation=1, max_anion=1)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

======================================================================
ERROR: horton.part.test.test_proatomdb.test_io_filename
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/test/test_proatomdb.py", line 114, in test_io_filename
    padb1 = ProAtomDB.from_refatoms(numbers=[1, 6], max_cation=1, max_anion=0)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

======================================================================
ERROR: horton.part.test.test_proatomdb.test_compute_radii
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/test/test_proatomdb.py", line 127, in test_compute_radii
    padb = ProAtomDB.from_refatoms([1, 6], 0, 0, (rgrid, 110))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

======================================================================
ERROR: horton.part.test.test_proatomdb.test_get_spline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/test/test_proatomdb.py", line 172, in test_get_spline
    padb = ProAtomDB.from_refatoms(numbers=[1, 6], max_cation=1, max_anion=1)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

======================================================================
ERROR: horton.scripts.test.test_atomdb.test_plot_atoms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pancha/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/scripts/test/test_atomdb.py", line 202, in test_plot_atoms
    padb = ProAtomDB.from_refatoms(numbers=[8, 1], max_cation=1, max_anion=1)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 457, in from_refatoms
    return cls.from_files(fns_chk, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 412, in from_files
    records.append(ProAtomRecord.from_iodata(mol, agspec))
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 65, in from_iodata
    return cls.from_dm(center, number, pseudo_number, iodata.obasis, dm_full, energy, agspec)
  File "/home/pancha/.local/lib/python2.7/site-packages/horton/part/proatomdb.py", line 105, in from_dm
    rho_all = obasis.compute_grid_density_dm(dm_full, atgrid.points)
  File "horton/gbasis/cext.pyx", line 1254, in horton.gbasis.cext.GOBasis.compute_grid_density_dm
  File "horton/gbasis/cext.pyx", line 1198, in horton.gbasis.cext.GOBasis._compute_grid1_dm
AttributeError: 'numpy.ndarray' object has no attribute '_array'

----------------------------------------------------------------------
Ran 1168 tests in 717.577s

FAILED (errors=6)
```

**Comment by tovrstra** [comment]
I would recommend to just download version 2.1.1, instead of the last commit from the git repository. The master branch contains a lot of experimental changes, which are non-trivial to get to work.

**Comment by panchajaviera** [comment]
That's the version I downloaded from here: https://theochem.github.io/horton/2.1.1/user_download_and_install_linux.html

**Comment by tovrstra** [comment]
OK. I misinterpreted some of the output you pasted. Could your run the following and then try to install and run the tests again? There seem to be some leftovers in these files that are reminiscent to the code on the master branch.

```bash
# Starting from the source tree where you unpacked the horton release:
cd data/refatoms
rm *.h5
make
cd ../..
```

**Comment by tovrstra** [comment]
@panchajaviera I found the cause of this problem. I made a small mistake in the release process. The 2.1.1 tar file contained an error and it is now replaced by a new one. Can you try the installation from scratch, i.e. after removing your old horton files and downloading the new tar file?

**Comment by panchajaviera** [comment]
@tovrstra I re-installed everything from scratch and now, after running nosetests it says "OK".
So, thank you for the help!

**Comment by tovrstra** [comment]
You're welcome!
